name: Build daily S&P500 snapshot

on:
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance pandas_ta requests

      - name: Build snapshot
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          ORATS_API_KEY:   ${{ secrets.ORATS_API_KEY }}
          NEWSAPI_KEY:     ${{ secrets.NEWSAPI_KEY }}
        run: |
          python scripts/build_snapshot.py

      - name: Commit snapshot
        run: |
          git config user.name  "sp500-bot"
          git config user.email "actions@users.noreply.github.com"
          git add docs/data/snapshot.json
          git commit -m "daily snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
